### ISSUE TITLE
Vim & JS

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#21]
Improve the Vim setup for JavaScript:

- [ ] Set up [Tern.js](http://ternjs.net/doc/manual.html) / [tern for vim](https://github.com/marijnh/tern_for_vim)
- [ ] Set up [neoformat & prettier](https://hashrocket.com/blog/posts/writing-prettier-javascript-in-vim)

**Comment by moonglum** [comment]
The result is: It is pretty awesome. Need to find out how to get Vim 8 to compile with Python binding stuff.

**Comment by bitboxer** [comment]
Lots of JS? Poor @moonglum 😉

**Comment by moonglum** [comment]
Heh, that was 2014 ^^ Those times are over 😆

**Comment by moonglum** [comment]
All of this now works via ale, and I like it!
