### ISSUE TITLE
Vim & LaTeX and Markdown

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#31]
- [Words to avoid in tech writing](http://wynnnetherland.com/linked/2014010902/words-to-avoid-in-tech-writing)
- [My Ph.D. advisor rewrote himself in bash](http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates)
- [Vimtex](https://wikimatze.de/vimtex-the-perfect-tool-for-working-with-tex-and-vim/)
- [Tectonic](https://tectonic-typesetting.github.io/en-US/)

**Comment by moonglum** [comment]
2014. What a year! I guess... I'm not writing as much LaTeX nowadays :sweat_smile:

**Comment by bitboxer** [comment]
At least you did follow my advice and did not procrastinate on this one 😅😅
