### ISSUE TITLE
Try out nvim

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#46]
* [x] [How to install nvim on Ubuntu](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu).
* [ ] [How to migrate from vim](https://wiki.archlinux.org/index.php/Neovim)

Exciting plugins:

* [neomake](https://github.com/benekastah/neomake), replacing dispatch
* [fzf](https://github.com/junegunn/fzf), replacing ctrlp
* [neoterm](https://github.com/kassio/neoterm)
* [deoplete](https://github.com/Shougo/deoplete.nvim)

**Comment by bitboxer** [comment]
Son, come over to our side. It is the better one :wink:

![9zc7wc](https://cloud.githubusercontent.com/assets/56195/11713329/09fccb7e-9f33-11e5-91c3-6c79d70cbdf9.gif)

**Comment by moonglum** [comment]
Hehe, thought you would like that :smile: Any other exciting plugins? :smile:

**Comment by bitboxer** [comment]
If you haven't made the switch yet: VimPlug is really awesome (not neovim specific). The "PlugUpdate" with commit notifications that show you what changed in the plugins is really helpful sometimes.

And I don't use it mainly because of the plugins, but because it is faster and has less of the OS/2 and Atari code :wink:

**Comment by moonglum** [comment]
In my current setup, I use the good old Pathogen and use Ansible to install the plugins and keep them up to date :smile: 

Hehe, ok :smile:

**Comment by moonglum** [comment]
@bitboxer When I load my .vim config in nvim, the startup time is ridiciously slow. It's so slow that it's not acceptable. vim starts instantaneously with the same configuration. Any ideas why that happens?

**Comment by bitboxer** [comment]
Lets pair on that one. Mine is like super fast and stuff.

In the meantime, here is a Rick and Morty Music Video to watch while you wait for `nvim` to start:

[<img width="832" alt="bildschirmfoto 2016-01-23 um 05 42 30" src="https://cloud.githubusercontent.com/assets/56195/12528368/21014a88-c194-11e5-8cf3-6739de9cc00f.png">](https://www.youtube.com/watch?v=TgqiSBxvdws)

**Comment by moonglum** [comment]
Okidoke! :smile:

**Comment by moonglum** [comment]
Thanks for your help, @bitboxer :heart:
