### ISSUE TITLE
List of tools to try

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#53]
## CLI Apps

- [ ] [ru](http://www.sitepoint.com/ru-ruby-shell/) for one liner
- [x] [mdless](http://brettterpstra.com/projects/mdless/) for Markdown Previews
- [ ] I want to try out [Org mode](http://orgmode.org). It seems to be super interesting.
    - [Introduction video](https://www.youtube.com/watch?v=oJTwQvgfgMM)
    - [org-ref](https://twitter.com/lispmeister/status/689101655661481984)
- [ ] [fzf](https://github.com/junegunn/fzf): A fuzzy finder for the shell. That thing is awesome. You can switch branches, kill processes and many things more with a fuzzy finder. [Bodos config for it](https://github.com/bitboxer/dotfiles/blob/master/tilde/zsh/fzf.sh).

## GUI Apps

- [ ] [postman](https://www.getpostman.com/) for API exploring
- [ ] [SQL Tabs](http://www.sqltabs.com/) as a desktop client for Postgresql
- [ ] [dbglass](http://dbglass.web-pal.com/)
- [ ] [vim mode for Atom](https://atom.io/packages/vim-mode-plus)
- [ ] [Insomnia](https://insomnia.rest)

## Ruby Libraries

- [ ] [administrate](https://github.com/thoughtbot/administrate) as a replacement for activeadmin
- [ ] [shrine](http://twin.github.io/introducing-shrine) as a replacement for CarrierWave
- [ ] [formular](https://github.com/apotonick/formular) as a replacement for SimpleForm
- [ ] [http.rb](https://github.com/httprb/http/wiki)
- [ ] [oga](https://github.com/yorickpeterse/oga/)
- [ ] [HexaPDF](http://hexapdf.gettalong.org)

**Comment by bitboxer** [comment]
Sadly hurley is marked as dead :sob: . I use it in 2 projects of customers and need to switch them to faraday someday in the next half year or so.

**Comment by bitboxer** [comment]
Details here: https://github.com/lostisland/hurley/issues/43

**Comment by moonglum** [comment]
Sigh, it looked very promising :cry:

**Comment by bitboxer** [comment]
Yep. That's the reason why i started to use it 😢

**Comment by halostatue** [comment]
Just as a note, my team at Kinetic Cafe has expressed an interest to me in forking/continuing Hurley, and we are going to look at starting that in the near future.

**Comment by bitboxer** [comment]
Awesome!

**Comment by moonglum** [comment]
:sparkles:
