### ISSUE TITLE
Vim & Elixir

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#59]
Improve the Vim setup for Elixir:

- [ ] [Hashrocket](https://til.hashrocket.com/posts/683146740a-documentation-lookup-with-vim-and-alchemist)
- [ ] [Bodo](https://bitboxer.de/2016/11/13/vim-for-elixir)
- [ ] [alchemist-vim](https://github.com/slashmili/alchemist.vim)

**Comment by bitboxer** [comment]
I am a todo in your list. So proud of myself 😻🙋

**Comment by moonglum** [comment]
Heh, I just don't really do Elixir :sweat_smile: So I'll close this. Sorry, Bodo <3

**Comment by bitboxer** [comment]
You are saying this now, but let's wait a few years 🤣😘.

**Comment by moonglum** [comment]
Hehe, let's do that 😉 I'll ask you again, then 😘
