### ISSUE TITLE
Tools for better writing

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#65]
* https://github.com/btford/write-good
* https://github.com/Heydon/readabilityCheckerCLI
* http://proselint.com/

**Comment by bitboxer** [comment]
I am also interested in write-good for neomake. Sadly the last release was in feb 2015, there is a lot of development on github, but no release. I asked in that repo for when the next release might be. Let's see how it goes :wink:

**Comment by moonglum** [comment]
This sounds like a good idea, yes! 😄

**Comment by moonglum** [comment]
I'm currently using proselint & alex via ale 👍
