### ISSUE TITLE
xsel

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#69]
Make the pinboard from macOS available within the machine and vice-versa. @bitboxer did that via [xsel](https://wiki.ubuntuusers.de/xsel/). I suspect it also has something to do with [forwarding x11](https://github.com/bitboxer/dotfiles/blob/vagrant-it/Vagrantfile#L8)

**Comment by bitboxer** [comment]
Yes, forwarding X11 is the key 👍

**Comment by bitboxer** [comment]
We can do a pairing session on that if you want.

**Comment by moonglum** [comment]
Would appreciate that 😄 I always get

```
xsel: Can't open display: (null)
: Inappropriate ioctl for device
```

when I do a `echo "Hallo Welt" | xsel -bi`
