### ISSUE TITLE
Try out orbacle

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#77]
[orbacle](https://github.com/swistak35/orbacle) allows for smart jump-to-definitions, autocompletion, constant renaming and more in Ruby.

**Comment by bitboxer** [comment]
I am using [solargraph](https://github.com/castwide/solargraph) for my vs code setup and really like it so far. Maybe also worth a try.

**Comment by moonglum** [comment]
Thanks for the hint 👍

**Comment by moonglum** [comment]
I'm using solargraph with ale now – works well 👍
