### ISSUE TITLE
Find a good solution for umlauts on Linux

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#89]
Fix umlauts... I'm lost :joy: Maybe I'll fix it [via my keyboard](https://github.com/qmk/qmk_firmware/tree/master/keyboards/planck/keymaps/spacebarracecar), propably by providing a [AltGr + compose](https://ar.al/2018/07/18/typographical-typing-habits-for-linux) mapping.

**Comment by bitboxer** [comment]
I fixed it with my ergodox firmware, too. Linux keyboard mapping is soo bad that I switched everything to firmware :) . 

Something like Karabiner is really missing on Linux.

**Comment by moonglum** [comment]
And you're using a German keyboard layout from the perspective of the OS?

**Comment by bitboxer** [comment]
No, from the OS I am using an american layout, luckily my firmware can do macros that can fire "umlaut key + A" and other things.

**Comment by bitboxer** [comment]
I tried the german layout, but that had weird side effects.

**Comment by moonglum** [comment]
I'm using a Planck, so we should be using the same firmware. Are you using [Oryx](https://configure.zsa.io) to configure your keyboard? If so, can you send me a link to your layout?

**Comment by bitboxer** [comment]
Will sent tomorrow when I am back on a computer. But it's nothing special, just sending Alt+U and then A.

**Comment by bitboxer** [comment]
On ubuntu you have a settings dialog for it: https://help.ubuntu.com/stable/ubuntu-help/tips-specialchars.html.en#compose

**Comment by moonglum** [comment]
Moved to https://codeberg.org/moonglum/dotfiles/issues/5
